# Generated by Django 2.2.7 on 2019-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191120_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='myimage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
