# Generated by Django 2.2.7 on 2019-11-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog_myimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='myimage',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
